name: Android Pipeline
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Grant Execution Permission
        run: chmod +x ./gradlew
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Set up Android SDK
        uses: actions/setup-android@v2
        with:
          android-sdk-license: accept
      - name: Assemble Debug
        run: ./gradlew assembleDebug --kotlin-dsl
